import { SkillCategories, SkillsDatabase, SkillTypes } from '@/Enums/Skill'
import { Database } from '@/Interfaces/Layout'
import { Skill } from '@/Interfaces/Skill'

export const SkillsDatabaseMap: Database<Skill> = {
	/* Languages */
	[SkillsDatabase.JavaScript]: {
		Name: 'JavaScript',
		IsMainSkill: true,
		Category: SkillCategories.ProgrammingLanguages,
		SkillType: SkillTypes.Technology,
		RelatedSkills: [
			SkillsDatabase.AngularJS,
			SkillsDatabase.ClerkAuth,
			SkillsDatabase.ESLint,
			SkillsDatabase.ExpressJS,
			SkillsDatabase.Jest,
			SkillsDatabase.Mongoose,
			SkillsDatabase.NextAuth,
			SkillsDatabase.NextJS,
			SkillsDatabase.NPM,
			SkillsDatabase.NuxtJS,
			SkillsDatabase.NxJS,
			SkillsDatabase.PNPM,
			SkillsDatabase.Prettier,
			SkillsDatabase.ReactJS,
			SkillsDatabase.Recoil,
			SkillsDatabase.Redux,
			SkillsDatabase.SvelteJS,
			SkillsDatabase.SvelteKit,
			SkillsDatabase.Vitest,
			SkillsDatabase.VueJS,
			SkillsDatabase.Yarn,
		],
	},
	[SkillsDatabase.Python]: {
		Name: 'Python',
		IsMainSkill: true,
		Category: SkillCategories.ProgrammingLanguages,
		SkillType: SkillTypes.Technology,
		RelatedSkills: [
			SkillsDatabase.ArtificialIntelligence,
			SkillsDatabase.DataScience,
			SkillsDatabase.DataVisualization,
			SkillsDatabase.DeepLearning,
			SkillsDatabase.Django,
			SkillsDatabase.Flask,
			SkillsDatabase.Gunicorn,
			SkillsDatabase.HyperParameters,
			SkillsDatabase.Jinja,
			SkillsDatabase.Jupyter,
			SkillsDatabase.Keras,
			SkillsDatabase.MachineLearning,
			SkillsDatabase.MatPlotLib,
			SkillsDatabase.NeuralNetworks,
			SkillsDatabase.NumPy,
			SkillsDatabase.Pandas,
			SkillsDatabase.Poetry,
			SkillsDatabase.PyBuilder,
			SkillsDatabase.PyLint,
			SkillsDatabase.PyTest,
			SkillsDatabase.Pip,
			SkillsDatabase.SciKitLearn,
			SkillsDatabase.SeaBorn,
			SkillsDatabase.SimpleGUI,
			SkillsDatabase.SQLAlchemy,
			SkillsDatabase.UnitTest,
			SkillsDatabase.WebDevelopment,
		],
	},
	[SkillsDatabase.TypeScript]: {
		Name: 'TypeScript',
		IsMainSkill: true,
		Category: SkillCategories.ProgrammingLanguages,
		SkillType: SkillTypes.Technology,
		RelatedSkills: [
			SkillsDatabase.AngularJS,
			SkillsDatabase.ClerkAuth,
			SkillsDatabase.ESLint,
			SkillsDatabase.ExpressJS,
			SkillsDatabase.Jest,
			SkillsDatabase.Mongoose,
			SkillsDatabase.NextAuth,
			SkillsDatabase.NextJS,
			SkillsDatabase.NPM,
			SkillsDatabase.NuxtJS,
			SkillsDatabase.NxJS,
			SkillsDatabase.PNPM,
			SkillsDatabase.Prettier,
			SkillsDatabase.ReactJS,
			SkillsDatabase.Recoil,
			SkillsDatabase.Redux,
			SkillsDatabase.SvelteJS,
			SkillsDatabase.SvelteKit,
			SkillsDatabase.TypeORM,
			SkillsDatabase.Vitest,
			SkillsDatabase.VueJS,
			SkillsDatabase.Yarn,
			SkillsDatabase.Zod,
		],
	},

	/* Soft Skills */
	[SkillsDatabase.Adaptability]: {
		Name: 'Adaptability',
		IsMainSkill: false,
		Category: SkillCategories.SoftSkills,
		SkillType: SkillTypes.Soft,
	}
}

export const SkillsDatabaseKeys: SkillsDatabase[] = Object.keys(SkillsDatabaseMap) as SkillsDatabase[]