export enum GroupByOptions {
	Category = 'Category',
    Language = 'Language',
    SkillType = 'Skill-Type',
}

export enum SkillCategories {
    ArtificialIntelligence = 'Artificial Intelligence (AI)',
    Automation = 'Automation',
    BackEndWebDevelopment = 'Back-End Web Development',
    CloudComputing = 'Cloud Computing',
    CodeQuality = 'Code Quality',
    CommunicationProtocolsLibraries = 'Communication Protocols & Libraries',
    ComputerScience = 'Computer Science',
    Database = 'Database',
    DataEngineering = 'Data Engineering',
    DataScience = 'Data Science',
    Deployment = 'Deployment',
    DevOps = 'DevOps',
    FrontEndWebDevelopment = 'Front-End Web Development',
    FullStackWebDevelopment = 'Full-Stack Web Development',
    GameDevelopment = 'Game Development',
    Internet = 'Internet',
    JavaScript = 'JavaScript',
    MachineLearningEngineering = 'Machine Learning Engineering',
    Mathematics = 'Mathematics',
    Network = 'Network',
    PlatformDevelopment = 'Platform Development',
    ProgrammingLanguages = 'Programming Languages',
    ProjectManagement = 'Project Management',
    Python = 'Python',
    Security = 'Security',
    SoftSkills = 'Soft Skills',
    Testing = 'Testing',
    VersionControl = 'Version Control',
}

export enum SkillsDatabase {
	/* Languages */
    C = 'C',
    FunctionalProgramming = 'Functional-Programming',
    GameMakerLanguage = 'Game-Maker-Language',
    Groovy = 'Groovy',
    Haskell = 'Haskell',
    Java = 'Java',
    JavaScript = 'JavaScript',
    Kotlin = 'Kotlin',
    ObjectOrientedProgramming = 'OOP',
    Python = 'Python',
    RLanguage = 'R',
    Scala = 'Scala',
    ShellScript = 'Shell',
    TypeScript = 'TypeScript',

    /* APIs */
    APIs = 'APIs',
    Apollo = 'Apollo',
    GraphQL = 'GraphQL-API',
    OpenAI = 'Open-AI',
    Pusher = 'Pusher',
    ReplicateAI = 'Replicate-AI',
    REST = 'REST-API',
    SDKs = 'SDKs',
    SocketIO = 'Socket-IO',
    TRPC = 'TRPC-API',

	/* Front-End Web Development */
    AntDesign = 'Ant-Design',
    Axios = 'Axios',
    Bootstrap = 'Bootstrap',
    ChakraUI = 'Chakra-UI',
    CSS = 'CSS',
	HandlebarsJS = 'Handlebars-JS',
    HeadlessUI = 'Headless-UI',
    HTML = 'HTML',
    Jotai = 'Jotai',
    MaterialUI = 'Material-UI',
    NextUI = 'Next-UI',
    RadixUI = 'Radix-UI',
    ReactJS = 'React',
    ReactQuery = 'React-Query',
    Recoil = 'Recoil',
    Redux = 'Redux',
    SemanticUI = 'Semantic-UI',
    ShadcnUI = 'Shadcn-UI',
    SimpleGUI = 'Simple-GUI',
    StateManagement = 'State-Management',
    StoryBooks = 'Storybooks',
    SvelteJS = 'Svelte',
    TailwindCSS = 'Tailwind-CSS',
    UserCentricDesign = 'User-Centric-Design',
    VueJS = 'Vue-JS',
    Zustand = 'Zustand',

    /* Back-End Web Development */
    Firebase = 'Firebase',
    Supabase = 'Supabase',
    PocketBase = 'PocketBase',
    Auth0 = 'Auth0',
    ClerkAuth = 'Clerk-Auth',
    NextAuth = 'Next-Auth',
    Stripe = 'Stripe',
    ExpressJS = 'Express-JS',
    Flask = 'Flask',
    Django = 'Django',
    Spring = 'Spring',
    SpringBoot = 'Spring-Boot',
    Cloudinary = 'Cloudinary',
    EdgeStore = 'Edge-Store',
    Gunicorn = 'Gunicorn',
    Jinja = 'Jinja',
    WebSockets = 'Web-Sockets',
    UserAuthentication = 'User-Authentication',

    /* Full-Stack Web Development */
    AngularJS = 'Angular-JS',
    NextJS = 'Next-JS',
    NuxtJS = 'Nuxt-JS',
    ProgressiveWebApps = 'Progressive-Web-Apps',
	SvelteKit = 'Svelte-Kit',

    /* Database */
    Convex = 'Convex',
    DatabaseIndexing = 'Database-Indexing',
    DatabaseManagementSystems = 'Database-Management-Systems',
    Databases = 'Databases',
    MongoDB = 'MongoDB',
    MySQL = 'MySQL',
    NonRelationalDatabases = 'Non-Relational-Databases',
    Normalization = 'Normalization',
    PostgreSQL = 'PostgreSQL',
	PSQL = 'PSQL',
    Redis = 'Redis',
    RelationalDatabases = 'Relational-Databases',
	Sequelize = 'Sequelize',
    SQL = 'SQL',

    /* Object-Relational Mappers */
    Drizzle = 'Drizzle',
    Hibernate = 'Hibernate',
    Mongoose = 'Mongoose',
    ObjectRelationalMapping = 'Object-Relational-Mapping',
    Prisma = 'Prisma',
    SQLAlchemy = 'SQLAlchemy',
    TypeORM = 'TypeORM',

    /* DevOps */
    Ansible = 'Ansible',
    Automation = 'Automation',
    Clusterization = 'Clusterization',
    Containerization = 'Containerization',
    ContinuousDelivery = 'Continuous-Delivery',
    ContinuousDeployment = 'Continuous-Deployment',
    ContinuousIntegration = 'Continuous-Integration',
    DevOps = 'Dev-Ops',
    Docker = 'Docker',
    GitHubActions = 'GitHub-Actions',
    GitHubPages = 'GitHub-Pages',
    GitLabCI = 'GitLab-CI',
    InfrastructureAsCode = 'Infrastructure-As-Code',
    Jenkins = 'Jenkins',
    Kubernetes = 'Kubernetes',
    Podman = 'Podman',
    TeamCity = 'Team-City',
    Terraform = 'Terraform',
    Vagrant = 'Vagrant',

    /* Version Control Systems */
    BitBucket = 'Bit-Bucket',
    Git = 'Git',
    GitHub = 'GitHub',
    GitLab = 'GitLab',
    VersionControlSystems = 'Version-Control-Systems',

    /* Code Quality */
    Black = 'Black',
    CheckStyle = 'CheckStyle',
    DesignPatterns = 'Design-Patterns',
	EditorConfig = 'Editor-Config',
    ESLint = 'ESLint',
    Linting = 'Linting',
    Prettier = 'Prettier',
    PyLint = 'PyLint',
    Zod = 'Zod',

    /* Testing */
    Cypress = 'Cypress',
    Jest = 'Jest',
    JUnit = 'JUnit',
    PyTest = 'PyTest',
    ReactTestingLibrary = 'React-Testing-Library',
    Testing = 'Testing',
    UnitTest = 'UnitTest',
    Vitest = 'Vitest',

    /* Project & Dependency Management */
    Gradle = 'Gradle',
    Maven = 'Maven',
	Node = 'Node-JS',
    NPM = 'NPM',
    NxJS = 'NX-JS',
    Pip = 'PIP',
    PNPM = 'PNPM',
    Poetry = 'Poetry',
    PyBuilder = 'PyBuilder',
    Tox = 'TOX',
    Yarn = 'Yarn',

    /* Artificial Intelligence, Machine Learning, & Data Science */
    ArtificialIntelligence = 'Artificial-Intelligence',
    Boosting = 'Boosting',
    DataScience = 'Data-Science',
    DeepLearning = 'Deep-Learning',
    DataVisualization = 'Data-Visualization',
    HyperParameters = 'HyperParameters',
    Jupyter = 'Jupyter',
    Keras = 'Keras',
    MachineLearning = 'Machine-Learning',
    MatPlotLib = 'MatPlotLib',
    NeuralNetworks = 'Neural-Networks',
    NumPy = 'NumPy',
    Pandas = 'Pandas',
    SciKitLearn = 'SciKit-Learn',
    SeaBorn = 'SeaBorn',

    /* Mathematics */
    Algebra = 'Algebra',
    Calculus = 'Calculus',
    Discrete = 'Discrete',
    Geometry = 'Geometry',
    LinearAlgebra = 'Linear-Algebra',
    Logics = 'Logics',
    Mathematics = 'Mathematics',
    Mechanics = 'Mechanics',
    Probability = 'Probability',
	RegExps = 'Regular-Expressions',
    Statistics = 'Statistics',
    Trigonometry = 'Trigonometry',

    /* Cloud Computing */
    AWS = 'AWS',
    AWS_CloudWatch = 'AWS-CloudWatch',
    AWS_ApplicationLoadBalancer = 'AWS-Application-Load-Balancer',
    AWS_ElasticCache = 'AWS-Elastic-Cache',
    AWS_K3s = 'AWS-K3S',
    AWS_EC2 = 'AWS-EC2',
    AWS_S3 = 'AWS-S3',
    AWS_VPC = 'AWS-VPC',
    AWS_Lambda = 'AWS-Lambda',
    AWS_ElasticFileSystem = 'AWS-Elastic-Filesystem',
    AWS_ElasticBlockStore = 'AWS-Elastic-Block-Store',
    AWS_RelationalDatabaseService = 'AWS-Relational-Database-Service',
    AWS_AutoScaling = 'AWS-Auto-Scaling',
    AWS_CloudFormation = 'AWS-Cloudformation',
    AWS_CloudFront = 'AWS-Cloudfront',
    AWS_ElasticBeanstalk = 'AWS-Elastic-Beanstalk',
    Azure = 'Azure',
    Azure_AppService = 'Azure-App-Service',
    Azure_Monitor = 'Azure-Monitor',
    Azure_BlobStorage = 'Azure-Blob-Storage',
    Azure_DurableFunctions = 'Azure-Durable-Functions',
    Azure_Functions = 'Azure-Functions',
    Azure_ResourceManager = 'Azure-Resource-Manager',
    Azure_ContainerRegistry = 'Azure-Container-Registry',
    CloudComputing = 'Cloud-Computing',
    GCP = 'GCP',
    GCP_AppEngine = 'GCP-App-Engine',
    GCP_CloudSQL = 'GCP-Cloud-SQL',
    GCP_CloudStorage = 'GCP-Cloud-Storage',
    GCP_CloudTasks = 'GCP-Cloud-Tasks',
    GCP_CloudScheduler = 'GCP-Cloud-Scheduler',
    GCP_Logging = 'GCP-Logging',

    /* Algorithms & Data Structures */
    Algorithms = 'Algorithms',
    DataStructures = 'Data-Structures',

    /* Platform Development */
    AndroidDevelopment = 'Android',
    iOSDevelopment = 'iOS',
    LinuxDevelopment = 'Linux',
    MacDevelopment = 'Mac',
    WebDevelopment = 'Web',
    WindowsDevelopment = 'Windows',

    /* Others */
    Networking = 'Networking',
    Symphony = 'Symphony',

    /* Security */
    Cryptography = 'Cryptography',
    CyberSecurity = 'Cyber-Security',
    Security = 'Security',

    /* Soft Skills */
    Adaptability = 'Adaptability',
    Communication = 'Communication',
    CostManagement = 'Cost-Management',
    Creativity = 'Creativity',
    CriticalThinking = 'Critical-Thinking',
    HumanResourceManagement = 'Human-Resource-Management',
    IntegrationManagement = 'Integration-Management',
    Leadership = 'Leadership',
    ProblemSolving = 'Problem-Solving',
    ProcurementManagement = 'Procurement-Management',
    ProjectManagement = 'Project-Management',
    QualityManagement = 'Quality-Management',
    RiskManagement = 'Risk-Management',
    ScopeManagement = 'Scope-Management',
    StakeholderManagement = 'Stakeholder-Management',
    Teamwork = 'Teamwork',
    TimeManagement = 'Time-Management',
}

export enum SkillTypes {
	Soft = 'Soft', /* Skills Not Related To Tech But Important For Professional Development (Communication, Teamwork, Problem-Solving) */
	Technical = 'Technical', /* Hard Skills That Don't Use Specific Technologies (Web Development, Software Engineering, Data Science) */
	Technology = 'Technology', /* Specific Technologies Like Specific Programming Languages, Frameworks, Other Skills That Require Practice & Knowledge */
}